development:
  store: redis_cache_store
  url: redis://localhost:6379/0

test:
  store: redis_cache_store
  url: redis://localhost:6379/1

production:
  store: redis_cache_store
  url: <%= ENV['REDIS_URL'] %>
